version: '3.8'

services:
  # Redis for buildfarm storage
  redis:
    image: redis:7-alpine
    container_name: buildfarm-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Buildfarm server (scheduler + CAS + ActionCache)
  buildfarm-server:
    image: bazelbuild/buildfarm-server:latest
    container_name: buildfarm-server
    ports:
      - "8980:8980"   # gRPC port for Remote Execution API
      - "8981:8981"   # HTTP port for web UI
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./config/server.config.example.yml:/app/server.config.yml:ro
      - buildfarm_cas:/tmp/buildfarm/cas
    environment:
      - CONFIG_FILE=/app/server.config.yml
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:8980"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Buildfarm worker
  buildfarm-worker:
    image: bazelbuild/buildfarm-worker:latest
    container_name: buildfarm-worker
    depends_on:
      buildfarm-server:
        condition: service_healthy
    volumes:
      - ./config/worker.config.example.yml:/app/worker.config.yml:ro
      - buildfarm_worker:/tmp/buildfarm/worker
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker-based execution
    environment:
      - CONFIG_FILE=/app/worker.config.yml
      - SERVER_HOST=buildfarm-server
      - SERVER_PORT=8980
    privileged: true  # Needed for sandboxed execution

volumes:
  redis_data:
    driver: local
  buildfarm_cas:
    driver: local
  buildfarm_worker:
    driver: local

networks:
  default:
    name: buildfarm-network