version: '3.8'

services:
  # BuildBarn - simpler alternative to Buildfarm for local development
  bb-scheduler:
    image: buildbarn/bb-scheduler:20230105T161545Z-6625bfe
    container_name: bb-scheduler
    ports:
      - "8980:8980"
    volumes:
      - ./config/bb-scheduler.json:/config/bb-scheduler.json:ro
    command: ["/bb_scheduler", "-config-path", "/config/bb-scheduler.json"]
    
  bb-worker:
    image: buildbarn/bb-worker:20230105T161545Z-6625bfe
    container_name: bb-worker
    depends_on:
      - bb-scheduler
    volumes:
      - ./config/bb-worker.json:/config/bb-worker.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bb_worker", "-config-path", "/config/bb-worker.json"]
    privileged: true

  # Simple Mock Remote Execution Server (for testing connectivity)
  simple-remote-exec:
    image: gcr.io/bazel-public/remote-execution-server:latest
    container_name: simple-remote-exec
    ports:
      - "8080:8080"  # This matches our Forge default endpoint
    command: ["/remote-execution-server", "--port", "8080", "--instance", "default"]